shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - 'langium@3.3.1'

packages:
  - docs

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
