shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - langium
  - chokidar
  - undici-types
  - semver

packages:
  - docs

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
